//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQUtil
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbQuestion
    {
        public int Id { get; set; }
        public string question { get; set; }
        public string goodanswer { get; set; }
        public string badanswer1 { get; set; }
        public string badanswer2 { get; set; }
        public string badanswer3 { get; set; }
    }
}
