//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQUtil
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbUser
    {
        public dbUser()
        {
            this.played = 0;
            this.win = 0;
            this.questions = 0;
            this.goodanswers = 0;
        }
    
        public string name { get; set; }
        public string pass { get; set; }
        public string email { get; set; }
        public short played { get; set; }
        public short win { get; set; }
        public short questions { get; set; }
        public short goodanswers { get; set; }
    }
}
