// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace LoginTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// müködik
        /// </summary>
        public void Bejelentkezes()
        {
            #region Variable Declarations
            WpfEdit uITextBoxUserEdit = this.UIWpfWindow.UITextBoxUserEdit;
            WpfEdit uITextBoxPassEdit = this.UIWpfWindow.UITextBoxPassEdit;
            WpfButton uIBejelentkezésButton = this.UIWpfWindow.UIBejelentkezésButton;
            #endregion

            // Type 'admin' in 'TextBoxUser' text box
            uITextBoxUserEdit.Text = this.BejelentkezesParams.UITextBoxUserEditText;

            // Click 'TextBoxPass' text box
            Mouse.Click(uITextBoxPassEdit, new Point(66, 17));

            // Type '********' in 'TextBoxPass' text box
            Keyboard.SendKeys(uITextBoxPassEdit, this.BejelentkezesParams.UITextBoxPassEditSendKeys, true);

            // Click 'Bejelentkezés' button
            Mouse.Click(uIBejelentkezésButton, new Point(38, 24));
        }
        
        #region Properties
        public virtual BejelentkezesParams BejelentkezesParams
        {
            get
            {
                if ((this.mBejelentkezesParams == null))
                {
                    this.mBejelentkezesParams = new BejelentkezesParams();
                }
                return this.mBejelentkezesParams;
            }
        }
        
        public UIWpfWindow UIWpfWindow
        {
            get
            {
                if ((this.mUIWpfWindow == null))
                {
                    this.mUIWpfWindow = new UIWpfWindow();
                }
                return this.mUIWpfWindow;
            }
        }
        #endregion
        
        #region Fields
        private BejelentkezesParams mBejelentkezesParams;
        
        private UIWpfWindow mUIWpfWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Bejelentkezes'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class BejelentkezesParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'admin' in 'TextBoxUser' text box
        /// </summary>
        public string UITextBoxUserEditText = "admin";
        
        /// <summary>
        /// Type '********' in 'TextBoxPass' text box
        /// </summary>
        public string UITextBoxPassEditSendKeys = "ltMtR4VOfdZS3D8xaljxesqUwEXKaQEX";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIWpfWindow : WpfWindow
    {
        
        public UIWpfWindow()
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            #endregion
        }
        
        #region Properties
        public WpfEdit UITextBoxUserEdit
        {
            get
            {
                if ((this.mUITextBoxUserEdit == null))
                {
                    this.mUITextBoxUserEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITextBoxUserEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "TextBoxUser";
                    #endregion
                }
                return this.mUITextBoxUserEdit;
            }
        }
        
        public WpfEdit UITextBoxPassEdit
        {
            get
            {
                if ((this.mUITextBoxPassEdit == null))
                {
                    this.mUITextBoxPassEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITextBoxPassEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "TextBoxPass";
                    #endregion
                }
                return this.mUITextBoxPassEdit;
            }
        }
        
        public WpfButton UIBejelentkezésButton
        {
            get
            {
                if ((this.mUIBejelentkezésButton == null))
                {
                    this.mUIBejelentkezésButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIBejelentkezésButton.SearchProperties[WpfButton.PropertyNames.Name] = "Bejelentkezés";
                    #endregion
                }
                return this.mUIBejelentkezésButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUITextBoxUserEdit;
        
        private WpfEdit mUITextBoxPassEdit;
        
        private WpfButton mUIBejelentkezésButton;
        #endregion
    }
}
